version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./:/app
#      - ./.env:/var/www/.env
#      - ./vendor:/var/www/vendor
    depends_on:
      - db
    command: "bash entrypoint.sh"

  composer:
    image: composer
    command: composer install
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: docker_bd
      POSTGRES_USER: user_pg
      POSTGRES_PASSWORD: mdp_pg
    networks:
      - app-network
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge
